"""adds column to chats

Revision ID: f9029014f9f8
Revises: 76948ebfbc0e
Create Date: 2025-04-11 10:59:57.450432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9029014f9f8'
down_revision: Union[str, None] = '76948ebfbc0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('chat_type', sa.Enum('Prompt', 'Response', name='chat_type_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'chat_type')
    # ### end Alembic commands ###
